services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ./scripts/entrypoint-dev.sh
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    environment:
      - USE_POLLING=1

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: botdb
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  db_data:
